cpf/urls.py
from django.urls import path

from . import views

app_name = 'cpf'

urlpatterns = [

    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/voltar/', views.voltar, name='voltar'),
    path('validate', views.validateCpf, name='validate'),
    path('generate', views.generateCpf, name='generate'),
    path('delete', views.delete, name='delete'),
]

cpfValidator/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('cpf.urls')),
    path('admin/', admin.site.urls),
]

cpf/models.py
# Create your models here.
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

cpf/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question
from django.utils import timezone
from .validate_cpf import validate_CPF
from .validate_cpf import gera_CPF



def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    context = {'latest_question_list': latest_question_list}
    return render(request, 'cpf/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question2 = str(question.question_text)
    check = validate_CPF(question2)

    return render(request, 'cpf/detail.html', {'question': question, 'check': check})


def validateCpf(request):
    cpf = Question(question_text=request.POST['cpf'], pub_date=timezone.now())
    cpf.save()
    return HttpResponseRedirect(reverse('cpf:index'))

def generateCpf(request):
    cpf = Question(question_text=gera_CPF(), pub_date=timezone.now())
    cpf.save()
    return HttpResponseRedirect(reverse('cpf:index'))

def delete(request):
    cpf = Question(question_text=request.POST['delete'], pub_date=timezone.now())
    cpf.delete()
    return HttpResponseRedirect(reverse('cpf:index'))
        
    
    # if check == "{} eh Valido".format(cpf):
    #     cpf.save()
    #     return render(request, 'cpf/validate.html', {'cpf': cpf, 'answer':check})
    # else:
    #     return render(request, 'cpf/validate.html', {'cpf': cpf, 'answer':check})

def voltar(request, question_id):

    return HttpResponseRedirect(reverse('cpf:index'))

cpf/templates/cpf/detail.html
{% extends 'cpf/base.html' %}

{% block content %}
<h2>{{ question.question_text }}{{check}}</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'cpf:voltar' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Voltar" >
</form>

<form action="{% url 'cpf:delete' %}" method="post">
        {% csrf_token %}
    <input type="hidden" name="delete" value="{{ question.question_text }}">
    <input type="submit" value="Em construcao">
</form>
{% endblock %}

cpf/templates/cpf/index.html
{% extends 'cpf/base.html' %}
{% block content %}
        {% if latest_question_list %}
        <ul>
                <h2>Lista de Todos os CPFS do banco</h2>
        {% for question in latest_question_list %}
    
                
                <h4><a href="{% url 'cpf:detail' question.id %}">{{ question.question_text }}</a></h4> 
           
    
        {% endfor %}
        </ul>
    {% else %}
        <p>Ainda nao tem cpf, cadastre um!.</p>
    {% endif %}
    
    <h1>{{ question.question_text }}</h1>
    
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
    <form action="{% url 'cpf:validate' %}" method="post">
    {% csrf_token %}
    <input type="number" name="cpf">
    <input type="submit">
    </form>
{% endblock %}

cpf/templates/cpf/validate.html
{{cpf.question_text}}{{answer}}